import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, CircleAlert, ClipboardCheck, Code2, FileDiff, FlaskConical, GitCompareArrows, ListChecks, ShieldCheck, TestTube2, X } from "lucide-react";
import { SectionHeading } from "@/components/app-shell";
import { ButtonLink } from "@/components/button";
import { SeverityBadge, StatusBadge } from "@/components/status-badge";
import { findingById, findings, type Finding } from "@/lib/proof-data";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/findings/$id")({
  loader: ({ params }) => { const finding = findingById(params.id); if (!finding) throw notFound(); return finding; },
  head: ({ loaderData }) => ({ meta: [
    { title: loaderData ? `${loaderData.title} · Proof | ProofPR` : "Finding not found | ProofPR" },
    { name: "description", content: loaderData ? `Review the claim, code evidence, reproduction, patch and verification for ${loaderData.title}.` : "This ProofPR finding could not be found." },
    { property: "og:title", content: loaderData ? `${loaderData.title} | ProofPR` : "Finding not found | ProofPR" },
    { property: "og:description", content: loaderData ? `Inspect the proof trail and final ${loaderData.final_status.toLowerCase()} status for ${loaderData.title}.` : "This ProofPR finding could not be found." },
    { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary" },
  ] }),
  notFoundComponent: () => <div className="py-20 text-center"><h1 className="text-2xl font-semibold">Finding not found</h1><ButtonLink to="/findings" className="mt-5">Back to findings</ButtonLink></div>,
  component: FindingDetail,
});

function CodeEvidence({ finding }: { finding: Finding }) {
  return <div className="overflow-x-auto rounded-md border border-code-border bg-code"><div className="flex min-w-max items-center justify-between border-b border-code-border px-4 py-2.5"><span className="font-mono text-[10px] text-muted-foreground">{finding.file}</span><span className="font-mono text-[10px] text-muted-foreground">TypeScript</span></div><div className="min-w-max py-3 font-mono text-[11px] leading-7 md:text-xs">{finding.code_evidence.map((row) => <div key={row.line} className={cn("flex pr-6", row.flagged && "border-l-2 border-danger bg-highlight-red")}><span className="w-14 shrink-0 select-none pr-5 text-right text-muted-foreground/60">{row.line}</span><span className={cn("whitespace-pre", row.flagged ? "text-danger" : "text-foreground/80")}>{row.code}</span></div>)}</div></div>;
}
function PatchDiff({ finding }: { finding: Finding }) {
  return <div className="overflow-x-auto rounded-md border border-code-border bg-code"><div className="flex min-w-max items-center justify-between border-b border-code-border px-4 py-2.5"><span className="font-mono text-[10px] text-muted-foreground">{finding.file}</span><span className="font-mono text-[10px] text-success">+{finding.patch_diff.filter((row) => row.type === "added").length} <span className="text-danger">−{finding.patch_diff.filter((row) => row.type === "removed").length}</span></span></div><div className="min-w-max py-3 font-mono text-[11px] leading-7 md:text-xs">{finding.patch_diff.map((row, index) => <div key={index} className={cn("flex pr-6", row.type === "removed" && "bg-highlight-red text-danger", row.type === "added" && "bg-highlight-green text-success", row.type === "context" && "text-foreground/80")}><span className="w-10 shrink-0 select-none pr-2 text-right text-muted-foreground/50">{row.oldLine ?? ""}</span><span className="w-10 shrink-0 select-none pr-2 text-right text-muted-foreground/50">{row.newLine ?? ""}</span><span className="w-5 shrink-0 select-none">{row.type === "removed" ? "−" : row.type === "added" ? "+" : " "}</span><span className="whitespace-pre">{row.code}</span></div>)}</div></div>;
}
function FindingDetail() {
  const finding = Route.useLoaderData();
  const isRejected = finding.status === "REJECTED";
  const isUnverified = finding.status === "UNVERIFIED";
  const passed = finding.adversarial_tests.filter((test) => test.passed).length;
  const currentIndex = findings.findIndex((item) => item.id === finding.id);
  const next = findings[(currentIndex + 1) % findings.length] ?? finding;
  return <div className="mx-auto max-w-[1080px]">
    <div className="mb-7 flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground"><Link to="/findings" className="flex items-center gap-1.5 hover:text-foreground"><ArrowLeft size={13}/> Findings</Link><ChevronRight size={12}/><span className="font-mono text-foreground">{finding.id}</span></div>
    <div className="mb-8 border-b border-border pb-8"><div className="mb-4 flex flex-wrap items-center gap-3"><SeverityBadge severity={finding.severity}/><span className="text-muted-foreground">·</span><span className="font-mono text-[11px] text-muted-foreground">{finding.file}:{finding.line}</span></div><div className="flex flex-wrap items-start justify-between gap-5"><div className="min-w-0"><h1 className="text-[26px] font-semibold leading-tight md:text-[34px]">{finding.title}</h1><p className="mt-3 text-xs text-muted-foreground">Verified against <span className="font-medium text-foreground">shop-api</span> · Pull request #42</p></div><StatusBadge status={finding.final_status} large/></div></div>
    <div id="proof-trail" className="scroll-mt-8"><div className="mb-7 flex items-center gap-3"><div className="flex size-7 items-center justify-center rounded-md border border-primary/30 bg-primary/10 text-primary"><ShieldCheck size={15}/></div><span className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">Proof trail</span><div className="h-px flex-1 bg-border"/></div>
    <div className="grid gap-x-8 gap-y-8 xl:grid-cols-[minmax(0,1fr)_260px]"><div className="min-w-0 space-y-9">
      <section><SectionHeading icon={CircleAlert} title="01 / Claim"/><div className="rounded-md border border-border bg-card p-5"><p className="text-[13px] leading-7 text-foreground/85">{finding.claim}</p></div></section>
      <section><SectionHeading icon={Code2} title="02 / Code evidence" aside={<span className="font-mono text-[10px] text-muted-foreground">LINE {finding.line}</span>}/><CodeEvidence finding={finding}/><p className="mt-2.5 text-[11px] text-muted-foreground">Highlighted line was identified as the relevant code path.</p></section>
      <section><SectionHeading icon={FlaskConical} title="03 / Reproduction" aside={<span className={cn("rounded border px-2 py-1 font-mono text-[10px] font-semibold", isRejected ? "border-danger/30 bg-danger/10 text-danger" : isUnverified ? "border-warning/30 bg-warning/10 text-warning" : "border-danger/30 bg-danger/10 text-danger")}>{isRejected ? "UNABLE TO REPRODUCE" : isUnverified ? "PENDING" : "BEFORE FIX: FAILED"}</span>}/><div className="overflow-hidden rounded-md border border-border bg-card"><div className="border-b border-border bg-soft px-5 py-3 font-mono text-[11px] text-foreground">{finding.reproduction_test}</div><div className="space-y-4 p-5"><div><div className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Scenario</div><p className="text-xs leading-6 text-foreground/85">{finding.scenario}</p></div><div className="grid gap-4 border-t border-border pt-4 sm:grid-cols-2"><div><div className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Expected</div><p className="text-xs leading-6 text-success">{finding.expected}</p></div><div><div className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Actual</div><p className={cn("text-xs leading-6", isRejected ? "text-success" : isUnverified ? "text-warning" : "text-danger")}>{finding.actual}</p></div></div></div></div></section>
      {isRejected && <section><SectionHeading icon={ShieldCheck} title="04 / Evidence discovered"/><div className="rounded-md border border-danger/20 bg-danger/5 p-5"><p className="text-xs leading-7 text-foreground/85">{finding.evidence_discovered}</p></div></section>}
      {finding.patch_diff.length > 0 && <section id="patch" className="scroll-mt-8"><SectionHeading icon={FileDiff} title="04 / Proposed fix" aside={<span className="text-[10px] text-success">PATCH APPLIED</span>}/><PatchDiff finding={finding}/></section>}
      {!isRejected && <section><SectionHeading icon={GitCompareArrows} title={`${finding.patch_diff.length ? "05" : "04"} / Adversarial verification`} aside={<span className={cn("font-mono text-[11px] font-semibold", passed === finding.adversarial_tests.length ? "text-success" : "text-warning")}>{passed}/{finding.adversarial_tests.length} passed</span>}/><div className="grid gap-2 sm:grid-cols-2">{finding.adversarial_tests.map((test) => <div key={test.name} className="flex min-h-11 items-center gap-2.5 rounded-md border border-border bg-card px-3.5 py-2.5"><span className={test.passed ? "text-success" : "text-warning"}>{test.passed ? <Check size={14}/> : <CircleAlert size={14}/>}</span><span className="font-mono text-[11px] text-foreground/85">{test.name}</span></div>)}</div></section>}
      <section><SectionHeading icon={TestTube2} title={`${isRejected ? "05" : finding.patch_diff.length ? "06" : "05"} / Regression`}/><div className="overflow-hidden rounded-md border border-border bg-card"><table className="w-full text-left text-xs"><thead className="border-b border-border bg-soft text-[10px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Suite</th><th className="px-5 py-3 text-right font-medium">Result</th><th className="hidden px-5 py-3 text-right font-medium sm:table-cell">Status</th></tr></thead><tbody>{([ ["Unit Tests", finding.regression.unit], ["Integration Tests", finding.regression.integration], ["Proof Tests", finding.regression.proof], ["Total", finding.regression.total] ] as const).map(([label, count]) => <tr key={label} className={cn("border-b border-border last:border-b-0", label === "Total" && "bg-soft font-semibold")}><td className="px-5 py-3.5">{label}</td><td className="px-5 py-3.5 text-right font-mono">{count[0]}/{count[1]}</td><td className="hidden px-5 py-3.5 text-right text-success sm:table-cell"><span className="inline-flex items-center gap-1"><Check size={12}/> Passed</span></td></tr>)}</tbody></table></div></section>
      <section className="rounded-md border border-border bg-card px-5 py-9 text-center"><div className="mb-4 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">Final proof status</div><StatusBadge status={finding.final_status} large/><p className="mx-auto mt-4 max-w-md text-xs leading-6 text-muted-foreground">{finding.reason}</p></section>
    </div><aside className="hidden xl:block"><div className="sticky top-6 rounded-md border border-border bg-card p-5"><div className="text-[11px] font-semibold">Verification steps</div><div className="mt-5 space-y-5">{[
      ["Claim", "Suspected issue identified", true], ["Code evidence", "Relevant line isolated", true], ["Reproduction", isRejected ? "Claim not reproduced" : isUnverified ? "Pending result" : "Bug reproduced", !isUnverified], ["Proposed fix", finding.patch_diff.length ? "Patch applied" : "No patch", finding.patch_diff.length > 0], ["Adversarial", `${passed}/${finding.adversarial_tests.length} checks passed`, passed === finding.adversarial_tests.length], ["Regression", "Test suites checked", true],
    ].map(([name, detail, done], index) => <div key={String(name)} className="flex gap-3"><div className="flex flex-col items-center"><span className={cn("flex size-5 shrink-0 items-center justify-center rounded-full border", done ? "border-success/30 bg-success/10 text-success" : "border-border bg-soft text-muted-foreground")}>{done ? <Check size={11}/> : <span className="size-1 rounded-full bg-current"/>}</span>{index < 5 && <span className="mt-1 h-5 w-px bg-border"/>}</div><div><div className={cn("text-[11px] font-medium", !done && "text-muted-foreground")}>{String(name)}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{String(detail)}</div></div></div>)}</div><div className="mt-6 border-t border-border pt-4"><div className="text-[10px] text-muted-foreground">Finding ID</div><div className="mt-1 font-mono text-xs">{finding.id}</div></div></div></aside></div></div>
    <div className="mt-10 flex items-center justify-between gap-4 border-t border-border pt-6"><ButtonLink to="/findings"><ArrowLeft size={13}/> All findings</ButtonLink><ButtonLink to="/findings/$id" params={{ id: next.id }}>Next finding <ArrowRight size={13}/></ButtonLink></div>
  </div>;
}
