/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as FindingsIndexRouteImport } from './routes/findings.index'
import { Route as FindingsIdRouteImport } from './routes/findings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FindingsRoute,
} as any)
const FindingsIdRoute = FindingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FindingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/findings': typeof FindingsRouteWithChildren
  '/findings/$id': typeof FindingsIdRoute
  '/findings/': typeof FindingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/findings/$id': typeof FindingsIdRoute
  '/findings': typeof FindingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/findings': typeof FindingsRouteWithChildren
  '/findings/$id': typeof FindingsIdRoute
  '/findings/': typeof FindingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/findings' | '/findings/$id' | '/findings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/findings/$id' | '/findings'
  id: '__root__' | '/' | '/findings' | '/findings/$id' | '/findings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindingsRoute: typeof FindingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/': {
      id: '/findings/'
      path: '/'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof FindingsRoute
    }
    '/findings/$id': {
      id: '/findings/$id'
      path: '/$id'
      fullPath: '/findings/$id'
      preLoaderRoute: typeof FindingsIdRouteImport
      parentRoute: typeof FindingsRoute
    }
  }
}

interface FindingsRouteChildren {
  FindingsIdRoute: typeof FindingsIdRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
}

const FindingsRouteChildren: FindingsRouteChildren = {
  FindingsIdRoute: FindingsIdRoute,
  FindingsIndexRoute: FindingsIndexRoute,
}

const FindingsRouteWithChildren = FindingsRoute._addFileChildren(
  FindingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindingsRoute: FindingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
